// `gaia plugin migrate <dir>` — turns ONE existing gaia-format plugin package
// (plugin.json + conventional index.mjs, see manifest.ts) into a pi package in
// place: writes/updates package.json (adds a `pi.extensions` entry, never
// clobbers unrelated fields) and a generated pi-extension.mjs (see
// pi-adapter.ts). Idempotent — rerunning on an already-migrated dir is a
// no-op diff (same generated bytes, same merged package.json).
//
// Reuses the SAME hardened manifest reader/validator the daemon's own runtime
// plugin loader uses (readPluginManifest) rather than re-parsing plugin.json
// ad hoc — a dir that fails validation there is rejected here too, honestly.

import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { readPluginManifest, type ValidatedPluginManifest } from "./manifest.js";
import { generatePiExtensionEntry, mergePiPackageJson } from "./pi-adapter.js";

export const PI_EXTENSION_ENTRY_FILENAME = "pi-extension.mjs";

export type MigrateStatus = "migrated" | "up-to-date" | "skipped";

export interface MigrateResult {
  readonly dir: string;
  readonly status: MigrateStatus;
  readonly pluginId?: string;
  readonly reason?: string;
  readonly packageJsonPath?: string;
  readonly entryPath?: string;
  /** Deprecated contribution kinds (commands/tools/providers) this migration
   * moved into the generated pi-extension.mjs, one entry per kind with its
   * declared name count, e.g. "commands(3)". Empty when the plugin declares
   * none (doctrine, docs/PLUGIN-FORMAT.md). */
  readonly movedToPi?: readonly string[];
  /** channel-bridge contributions — no pi ExtensionAPI equivalent, stay
   * daemon-side indefinitely (contracts.ts). Empty when the plugin declares
   * none. */
  readonly stayedDaemon?: readonly string[];
}

function contributionSummary(manifest: ValidatedPluginManifest): { movedToPi: readonly string[]; stayedDaemon: readonly string[] } {
  const { commands, tools, providers, channels } = manifest.manifest.contributes;
  const movedToPi: string[] = [];
  if (commands.length > 0) movedToPi.push(`commands(${commands.length})`);
  if (tools.length > 0) movedToPi.push(`tools(${tools.length})`);
  if (providers.length > 0) movedToPi.push(`providers(${providers.length})`);
  const stayedDaemon: string[] = [];
  if (channels.length > 0) stayedDaemon.push(`channel-bridge(${channels.length})`);
  return { movedToPi, stayedDaemon };
}

async function readManifestForDir(dir: string): Promise<ValidatedPluginManifest> {
  const manifestPath = join(dir, "plugin.json");
  return readPluginManifest(manifestPath, { pluginsRoot: dirname(dir) });
}

async function readJsonIfExists(path: string): Promise<Record<string, unknown> | undefined> {
  if (!existsSync(path)) return undefined;
  const raw = await readFile(path, "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(`${path} must be a JSON object`);
  }
  return parsed as Record<string, unknown>;
}

/** Migrate one plugin directory. Never throws for an expected "not a package"
 * condition (missing plugin.json, missing index.mjs) — returns status
 * "skipped" with the real reason instead, so a batch run over many dirs can
 * report every outcome without aborting on the first non-package dir. */
export async function migratePluginDir(dir: string): Promise<MigrateResult> {
  let manifest: ValidatedPluginManifest;
  try {
    manifest = await readManifestForDir(dir);
  } catch (error) {
    return { dir, status: "skipped", reason: error instanceof Error ? error.message : String(error) };
  }

  const entryPath = join(dir, PI_EXTENSION_ENTRY_FILENAME);
  const packageJsonPath = join(dir, "package.json");
  const generatedEntry = generatePiExtensionEntry({ id: manifest.manifest.id });

  const existingEntry = existsSync(entryPath) ? await readFile(entryPath, "utf8") : undefined;
  const existingPackageJson = await readJsonIfExists(packageJsonPath);
  const mergedPackageJson = mergePiPackageJson(existingPackageJson, {
    name: manifest.manifest.id,
    version: manifest.manifest.version,
    description: `gaia plugin ${manifest.manifest.id} (migrated to a pi package by \`gaia plugin migrate\`)`,
    entryRelPath: `./${PI_EXTENSION_ENTRY_FILENAME}`,
  });
  const mergedText = `${JSON.stringify(mergedPackageJson, null, 2)}\n`;
  const existingText = existingPackageJson ? `${JSON.stringify(existingPackageJson, null, 2)}\n` : undefined;

  const entryChanged = existingEntry !== generatedEntry;
  const packageJsonChanged = existingText !== mergedText;

  if (entryChanged) await writeFile(entryPath, generatedEntry, "utf8");
  if (packageJsonChanged) await writeFile(packageJsonPath, mergedText, "utf8");

  const { movedToPi, stayedDaemon } = contributionSummary(manifest);
  return {
    dir,
    status: entryChanged || packageJsonChanged ? "migrated" : "up-to-date",
    pluginId: manifest.manifest.id,
    packageJsonPath,
    entryPath,
    movedToPi,
    stayedDaemon,
  };
}

/** Batch helper: migrate every direct child directory of a plugins root
 * (bundled plugins/ or a global ~/.gaia/plugins/ dir), reporting per-dir
 * results — a non-package dir (no plugin.json) is reported skipped, not
 * fatal. */
export async function migratePluginsRoot(root: string, dirNames: readonly string[]): Promise<readonly MigrateResult[]> {
  const results: MigrateResult[] = [];
  for (const name of dirNames) {
    results.push(await migratePluginDir(join(root, basename(name))));
  }
  return results;
}
