// Doctrine (Pascal 09-05): gaia plugin = pi extension. No parallel gaia-only
// format. This module is a CODE GENERATOR, not a runtime library — it emits a
// self-contained ESM string with zero gaia-daemon imports, because the
// generated file must resolve standalone inside an arbitrary plugin
// directory (or a published pi package), independent of whether gaia-daemon
// itself is running from source or as a `bun build --compile` binary with no
// src/ tree on disk (see AGENTS.md "compiled bun app"). The plugin's own
// index.mjs keeps its existing gaia-format `register()` contract verbatim
// (see src/services/plugins/contracts.ts PluginContributionRegistration) —
// this module only wraps it for pi's ExtensionAPI (registerCommand/
// registerTool), never edits it.
//
// Mapping:
//   commands  -> pi.registerCommand   (full fidelity: reply -> sendMessage,
//                steer -> sendUserMessage({deliverAs:"steer"}))
//   tools     -> pi.registerTool      (generic passthrough TypeBox schema —
//                gaia tool contributions declare no JSON schema today; every
//                real migrated plugin as of 09-05 has an empty tools array,
//                so this path is written to spec but UNVERIFIED against a
//                live tool-contribution plugin)
//   channels, providers -> NO pi extension equivalent exists (pi.registerProvider
//                is an LLM MODEL provider, a different concept from gaia's
//                generic provider/channel-bridge ports) — logged via
//                console.warn at extension load, never silently dropped. Every
//                real migrated plugin as of 09-05 declares both empty, so this
//                is a documented compromise, not a live gap.
//
// Capability note (doctrine, not oversight): gaia's daemon-side CapabilityBroker
// (src/services/capabilities/broker.ts) gates command contributions BEFORE
// contribution.run() is called, for chat-issued commands crossing MULTIPLE
// users/agents in a shared room. A pi extension loaded inside one lane's own
// pi session has no such multi-tenant surface — the sandbox + trust tier IS
// the boundary there (AGENTS.md "Summons run autonomously behind sandbox +
// trust tier ... sandbox IS the boundary"), matching how pi's OWN built-in
// extensions work (no per-command approval layer in pi either). The generated
// entry therefore calls contribution.run() directly with a minimal
// {workspaceId, roomId, agentId} context instead of routing through the
// broker.

export interface PiAdapterManifest {
  readonly id: string;
}

/** Deterministic — same manifest.id always produces byte-identical output, so
 * `gaia plugin migrate` regenerating this file twice is a true no-op diff. */
export function generatePiExtensionEntry(manifest: PiAdapterManifest): string {
  const pluginId = manifest.id;
  return `// AUTO-GENERATED by \`gaia plugin migrate\` (gaia-daemon src/services/plugins/pi-adapter.ts).
// Do not hand-edit — rerun migrate after changing index.mjs or plugin.json.
// Wraps gaia plugin ${pluginId}'s index.mjs (gaia-format register() contract)
// as a pi extension. See pi-adapter.ts for the full mapping + doctrine notes.
import * as gaiaPlugin from "./index.mjs";

const PLUGIN_ID = ${JSON.stringify(pluginId)};

function baseContext(pi) {
  const root = (pi && pi.cwd) || process.cwd();
  return { homedir: root, workspaceId: "pi", roomId: "pi", agentId: "pi", workspaceRoot: root, agents: [] };
}

export default function (pi) {
  const registered = typeof gaiaPlugin.register === "function" ? gaiaPlugin.register() : { contributions: {} };
  const contributions = registered.contributions || {};

  for (const command of contributions.commands || []) {
    pi.registerCommand(command.name, {
      description: command.description || PLUGIN_ID,
      handler: async (argsStr) => {
        const args = argsStr && argsStr.trim().length > 0 ? argsStr.trim().split(/\\s+/) : [];
        const ctx = baseContext(pi);
        const result = await command.run(ctx, { args, pluginContext: ctx });
        if (result && typeof result.reply === "string" && result.reply.length > 0) {
          pi.sendMessage({ customType: \`gaia-plugin:\${PLUGIN_ID}\`, content: result.reply, display: result.reply });
        }
        if (result && typeof result.steer === "string" && result.steer.length > 0) {
          pi.sendUserMessage(result.steer, { deliverAs: "steer" });
        }
      },
    });
  }

  for (const tool of contributions.tools || []) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description || PLUGIN_ID,
      // Generic passthrough schema: gaia tool contributions declare no JSON
      // schema of their own (see contracts.ts PluginToolContribution) — this
      // TypeBox object schema accepts any argument shape. Written to spec;
      // UNVERIFIED against a live tool-contribution plugin (none exist as of
      // 09-05, see pi-adapter.ts header note).
      parameters: { type: "object", additionalProperties: true },
      execute: async (_toolCallId, params) => {
        const ctx = baseContext(pi);
        const result = await tool.execute(ctx, { arguments: params || {} });
        return {
          content: [{ type: "text", text: (result && result.content) || "" }],
          details: { isError: !!(result && result.isError) },
        };
      },
    });
  }

  if ((contributions.channels || []).length > 0) {
    console.warn(\`gaia plugin \${PLUGIN_ID}: channel-bridge contributions have no pi extension equivalent, skipped\`);
  }
  if ((contributions.providers || []).length > 0) {
    console.warn(\`gaia plugin \${PLUGIN_ID}: provider contributions have no pi extension equivalent (pi.registerProvider is model-provider only), skipped\`);
  }

  return { dispose() {} };
}
`;
}

/** Merge (never clobber) a `pi.extensions` entry into an existing package.json
 * object, or build a minimal fresh one. Idempotent: calling twice with the
 * same inputs produces a structurally identical object (JSON.stringify may
 * reorder only if the caller re-serializes with different key order, which
 * migrate.ts avoids by writing through this function alone). */
export function mergePiPackageJson(
  existing: Record<string, unknown> | undefined,
  options: { readonly name: string; readonly version: string; readonly description: string; readonly entryRelPath: string },
): Record<string, unknown> {
  const base: Record<string, unknown> = existing ? { ...existing } : {
    name: options.name,
    version: options.version,
    description: options.description,
    type: "module",
    private: true,
  };
  const pi = (base.pi && typeof base.pi === "object" ? { ...(base.pi as Record<string, unknown>) } : {}) as Record<string, unknown>;
  const extensions = Array.isArray(pi.extensions) ? [...(pi.extensions as unknown[])] : [];
  if (!extensions.includes(options.entryRelPath)) extensions.push(options.entryRelPath);
  pi.extensions = extensions;
  base.pi = pi;
  return base;
}
